// <auto-generated />
namespace ASP_MVC_PROJECT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_grades_and_subjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_grades_and_subjects));
        
        string IMigrationMetadata.Id
        {
            get { return "202101262024453_add_grades_and_subjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
